[FEAT] Article, Category 도메인 연관관계 매핑
LikeLion-3/donationProject pull request #69
Opened 2023-12-07 01:43 UTC by WOOK0112

## #️⃣연관된 이슈

> #61 

## 📝작업 내용

>  Article, Category 도메인 연관관계 매핑
>  매핑에 따른 Article CRUD 수정

- [x] 새로운 기능 추가
- [x] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

2023-12-07 03:56 UTC, Jyoungjo requested changes

2023-12-07 03:56 UTC, Jyoungjo commented on BE/src/main/java/com/myapp/warmwave/domain/category/service/CategoryService.java
>  public class CategoryService {
Transaction 설정 부탁드립니당

2023-12-07 03:56 UTC, Jyoungjo commented on BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
>      public Article createArticle(ArticlePostDto dto, List<MultipartFile> imageFiles) throws IOException {
Transaction 설정 다 해주세용

2023-12-07 08:52 UTC, havegrit reviewed
ManyToMany 부분만 수정해주시면 될 것 같습니다 !

2023-12-07 08:52 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/article/controller/ArticleController.java
추후에 DTO로 변환하여 데이터 받을 수 있도록 리팩토링 부탁드립니다 !!!

2023-12-07 08:52 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
> +@Transactional
`@Transactional(read only = true)`

2023-12-07 08:52 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/article/service/ArticleService.java
>      public Article updateArticle(Long articleId, ArticlePostDto dto, List<MultipartFile> imageFiles) throws IOException {
method 위에 `@Transactional` 어노테이션 작성

2023-12-07 08:52 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/category/controller/CategotyController.java
```java
@PostMapping("/get")
public ResponseEntity<List<CategoryDto>> getCategory(@RequestBody CategoryDto dto){...}
```
이부분 테스트 끝나시면 삭제해주세요 :)

2023-12-07 08:52 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/category/entity/Category.java
> +    @ManyToMany(mappedBy = "categories")
ManyToMany -> ManyToOne & OneToMany

2023-12-08 07:27 UTC, havegrit approved these changes

2023-12-08 07:27 UTC, havegrit commented on BE/src/main/java/com/myapp/warmwave/domain/article/entity/ArticleCategory.java
> +    public static ArticleCategory buildArticleCategory (Article article, Category category) {
메소드 이름 `of()` 메모

2023-12-08 07:29 UTC, Jyoungjo approved these changes

2023-12-08 07:30 UTC, merged